[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
